### ISSUE TITLE
Перемещение - Ктулха 

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#25]
При "выходе" из кухни аватар оказывается в самом доме, т.е. его неправильно перемещает. В результате из-за отсутствия дверей в самом доме, как контейнере, ничего больше сделать нельзя. Принадлежность точки многоугольнику.

**Comment by iillyyaa2033** [comment]
Починено коммитом iillyyaa2033/nmud-core@ea252dcf474b021ceb79d428c068c40476f2a36d
