### ISSUE TITLE
Подсказки при вводе команд

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#26]
Говорил, что поломал сокращение команд(осм, рассм; вместо: осмотреться, рассмотреть). Не в приоритете, но с ними куда удобней.

Нужны подсказки для:
- [x] Для веб-морды
- [x] Ктулхи

**Comment by iillyyaa2033** [comment]
А какую команду выбрать при вводе 'осм': 'осмотреть', 'осмотреться', 'осмеять'?

Думаю, чего-то вроде подсказок (как у гугла, например) будет достаточно.

**Comment by klessh** [comment]
Да, вполне.

**Comment by iillyyaa2033** [comment]
Нужны подсказки для:
- [ ] Для веб-морды
- [ ] Ктулхи

**Comment by iillyyaa2033** [comment]
Добавил подсказки у ктулхи коммитом iillyyaa2033/nmud-demo@f8ca24854181e2fbdb165a1e72fdebc5e293fa2b

**Comment by iillyyaa2033** [comment]
Добавил подсказки для веба коммитом iillyyaa2033/nmud-content@d78b395b203d3e0fffdff5280bb6f8fd43b0a4f8
