### ISSUE TITLE
Замечания 

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#3]
Нужен шаг сетки в 0.1 метра. 
Недорисовка горизонтальной составляющей сетки в альбомной ориентации. 
Падение редактора при максимальном уменьшении. 
Нужна возможность удалять объекты. 
Отрисовка надписей в одном и том же месте делает их нечитабельными.

**Comment by iillyyaa2033** [comment]
Принято.
@klessh на будущее - это пять различных issues.

**Comment by iillyyaa2033** [comment]
@klessh, Айзек сделяль! Закрываю этот issue.
