### ISSUE TITLE
Отображение дочерних объектов в редакторе

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#40]
В процессе создания самого города в редакторе, при условии что все улицы будут подобно первой разбиты на фрагменты, важно видеть на один уровень ниже(т.е. дома). На будущее, глубина детализации(прорисовки дочерних объектов) могла бы настраиваться для каждого уровня.

**Comment by iillyyaa2033** [comment]
А нормально написать, не?

**Comment by klessh** [comment]
Не придирайся, ты не знаешь в каких условиях я это писал!

А тут ступил, согласен.

Понял.

**Comment by iillyyaa2033** [comment]
Ты, конечно, меня извини, но придираться я все же буду... Несмотря на условия. (Наверное, хорошо, что я их не знаю.)

В общем, настройка глубины отрисовки будет. Не сразу, но будет.
