### ISSUE TITLE
Сетка

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#5]
Масштаб сетки с единичным отрезком в 0.5 метра должен появляться при бóльшем увеличении. Чтобы тем самым увеличить диапазон масштабов, соответсвующий единичному отрезку  в 1 метр.

**Comment by iillyyaa2033** [comment]
Тут немного другая ситуевина: пока что шаг в 0.1 и 0.01 метра отрисовать не получается. почему - хз.
Так что посмотрю, что можно сделать.

Пожалуйста, пиши issue попонятнее. Лучше всего, если они будут в духе: "Хочу, чтобы шаг в 0.5 метра появлялся когда я зуммирую вот досюдова (+ скрин)". Вот.

**Comment by iillyyaa2033** [comment]
Была бага. Я ее поправил. @klessh?
