### ISSUE TITLE
Цвета объектов

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#51]
Нужна возможность настройки цвета объекта в редакторе. Можно как в диалоге(прямой ввод RRGGBB). Желательно с 'запоминанием' цвета - чтобы потом была возможность выбрать, а не вводить по новой.
Говорили об этом ещё до появления редактора в текущем виде. При создании карты будет удобнее красить в разные цвета, по крайней мере, дома и улицы.

**Comment by iillyyaa2033** [comment]
Будя.
