### ISSUE TITLE
Снова сетка

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#57]
Жирная сетка с шагом 1 метр - не жирная с шагом 0.1 метра, с ними что-то не так. Цифры. Отправляю скрин.

**Comment by klessh** [comment]
+ границы комнаты отображаются неверно при приближении.

**Comment by iillyyaa2033** [comment]
За что открываешь новый issue, когда я еще старый не закрыл?

Направляю тебя обратно:
1. https://github.com/iillyyaa2033/nmud/issues/47
2. https://github.com/iillyyaa2033/nmud/issues/48

**Comment by klessh** [comment]
Смутила пометка 'feature', проблема была неотлагательна...критична...
