### ISSUE TITLE
Прозрачность объектов

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#65]
Если не затруднит, можешь сделать объекты чуть менее прозрачными. А то хуже различаются цвета.

Лучше, если прозрачность можно будет настраивать для отдельных объектов.

**Comment by klessh** [comment]
Лучше, если прозрачность можно будет настраивать для отдельных объектов.

**Comment by iillyyaa2033** [comment]
@klessh, сделано. Прозрачность задается там же, где и цвет.
