### ISSUE TITLE
Чрезмерное энергопотребление

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#8]
Запущенный клиент разогревает устройство и потребляет очень много энергии, что весьма ограничивает возможности

**Comment by iillyyaa2033** [comment]
Только это не клиент, а сервер. Греется, потому что сильно жрет проц. Это фундаментальная проблема. Пока не знаю, что делать, но в один прекрасный день решу и ее.

**Comment by iillyyaa2033** [comment]
@klessh, так закрываем issue или нет?

**Comment by klessh** [comment]
Закрываем: энергопотребляемость удовлетворяет
--
Отправлено из Mail.Ru для Android воскресенье, 26 марта 2017г., 01:58 +03:00 от iillyyaa2033  notifications@github.com :

**Comment by iillyyaa2033** [comment]
Ну хорошо тогда
