### ISSUE TITLE
Написать

### ISSUE THREAD

**Issue by klessh** [iillyyaa2033/nmud#9]
Применимо к неодушевленным объектам

Действие: появление надписи на сущности

Пример: "Написать  здесь родила крыса на стене"

Блоки:
[на _чем-то_] - куда пишем(сущность)
[что-либо] - что пишем(текст)

**Comment by iillyyaa2033** [comment]
Сделано!

Коммиты:
-  iillyyaa2033/nmud-core@4a022aaaddc6c1de4a90ce52405db025b26e791c
-  iillyyaa2033/nmud-content@4c9c5dbbf9bff2be9d4d270f36f87970ab120f0b
